training_kwargs:
  n_epochs: 100
  n_train_steps: 10000
  n_eval_steps: 100
    
open_env:
  env_kwargs:
    observation_kwargs:
      rbf_kernel_size: 33  # must be odd
      rbf_kernel_scale: 0.3
      location_noise_scale: 0.12
      noise_log_mean: -3
      noise_log_scale: 0.05
      noise_corruption_prob: 0.005
    height: 20
    width: 20
    map_height: 64
    state_rewards:
      210: 10
      0: -1
      399: -1
      19: -1
      380: -1
    end_state:
      - 210
      - 0
      - 399
      - 19
      - 380
    movement_penalty: -0.1
    n_states: 400
  test_start_state: 10

thread_the_needle:
  env_kwargs:
    observation_kwargs:
      rbf_kernel_size: 33  # must be odd
      rbf_kernel_scale: 0.3
      location_noise_scale: 0.12
      noise_log_mean: -3
      noise_log_scale: 0.05
      noise_corruption_prob: 0.005
    height: 20
    width: 20
    map_height: 64
    state_rewards:
      84: 100
      399: -1
      19: -1
      380: -1
    end_state:    
      - 84
      - 399
      - 19
      - 380
    movement_penalty: -0.1
    n_states: 400
  test_start_state: 215


thread_the_needle_small:
  env_kwargs:
    observation_kwargs:
      rbf_kernel_size: 33  # must be odd
      rbf_kernel_scale: 0.3
      location_noise_scale: 0.12
      noise_log_mean: -3
      noise_log_scale: 0.05
      noise_corruption_prob: 0.005
    height: 20
    width: 20
    map_height: 64
    state_rewards:
      84: 100
      399: -1
      19: -1
      380: -1
    end_state:    
      - 84
      - 399
      - 19
      - 380
    movement_penalty: -0.1
    n_states: 400
  test_start_state: 215

  